CC = g++

CFLAGS = -Wall -Wextra -Werror -Ithirdparty/ -Isrc/Hangman_lib -Ithirdparty/include -DSFML_STATIC

SFML_LIBS = -Lthirdparty/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lsfml-audio -lopengl32 -lfreetype -lwinmm -lgdi32

LIFE_SRC = src/Hangman_main/
LIBLIFE_SRC = src/Hangman_lib/

LIFE_OBJ = obj/src/Hangman_main/
LIBLIFE_OBJ = obj/src/Hangman_lib/

BIN = bin/

TEST_BIN = bin/Hangman_test/ 

SRC = src/

TEST = test/

TEST_OBJ = obj/test/

THIRDPARTY = thirdparty/

SRCS := $(shell find . -type f -name '*.cpp')
HDRS := $(shell find . -type f -name '*.h')

.PHONY: main

$(BIN)Hangman_main/main.out: $(LIFE_OBJ)main.o $(LIBLIFE_OBJ)liblife.a
	$(CC) $(CFLAGS) -o $@ $^ $(SFML_LIBS)
$(LIFE_OBJ)main.o: $(LIFE_SRC)main.cpp 
	$(CC) -c $(CFLAGS) -o $@ $^
$(LIBLIFE_OBJ)liblife.a: $(LIBLIFE_OBJ)HangmanGame.o $(LIBLIFE_OBJ)MainMenu.o 
	ar rcs $@ $^
$(LIBLIFE_OBJ)HangmanGame.o: $(LIBLIFE_SRC)HangmanGame.cpp
	$(CC) -c $(CFLAGS) -o $@ $^
$(LIBLIFE_OBJ)MainMenu.o: $(LIBLIFE_SRC)MainMenu.cpp
	$(CC) -c $(CFLAGS) -o $@ $^

.PHONY: test

test: $(BIN)Hangman_test/test
	./$<

$(BIN)Hangman_test/test: $(TEST_OBJ)ctest.o $(TEST_OBJ)main.o $(TEST_OBJ)testliblife.a 
	$(CC) $(CFLAGS) -o $@ $^ $(SFML_LIBS)
$(TEST_OBJ)ctest.o: $(TEST)ctest.cpp
	$(CC) -c $(CFLAGS) -o $@ $^
$(TEST_OBJ)main.o: $(TEST)main.cpp
	$(CC) -c $(CFLAGS) -o $@ $^
$(TEST_OBJ)testliblife.a: $(TEST_OBJ)MainMenu.o $(TEST_OBJ)HangmanGame.o
	ar rcs $@ $^
$(TEST_OBJ)HangmanGame.o: $(LIBLIFE_SRC)HangmanGame.cpp
	$(CC) -c $(CFLAGS) -o $@ $^
$(TEST_OBJ)MainMenu.o: $(LIBLIFE_SRC)MainMenu.cpp
	$(CC) -c $(CFLAGS) -o $@ $^

.PHONY: clean

clean:
	rm -rf $(LIFE_OBJ)*.o
	rm -rf $(LIBLIFE_OBJ)*.o
	rm -rf $(LIBLIFE_OBJ)*.a
	rm -rf $(TEST_OBJ)*.o
	rm -rf $(TEST_OBJ)*.a
	rm -rf $(BIN)*.out

.PHONY: format

format:
	clang-format -i $(SRCS) $(HDRS)
